# Generated by Django 3.2 on 2021-05-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_ordermodel_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='order', to='customer.OrderItem'),
        ),
    ]
