# Generated by Django 3.2 on 2021-05-24 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_ordermodel_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.menuitem'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(related_name='order', to='customer.OrderItem'),
        ),
    ]
