# Generated by Django 3.2 on 2021-05-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_ordermodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
