# Generated by Django 3.2 on 2021-05-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210524_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered',
            field=models.IntegerField(default=0),
        ),
    ]
