# Generated by Django 3.2 on 2021-05-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
