# Generated by Django 3.2 on 2021-05-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_orderitem_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(to='customer.OrderItem'),
        ),
    ]
