# Generated by Django 3.2 on 2021-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210526_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='video_url',
            field=models.CharField(default='https://www.youtube.com/embed/gw27xRe1lCY', max_length=100),
        ),
    ]
