# Generated by Django 3.2 on 2021-05-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_menuitem_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
