# Generated by Django 3.2 on 2021-06-01 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0013_auto_20210531_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='ordered',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='permit_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='permitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
