# Generated by Django 3.2 on 2021-06-01 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0014_auto_20210601_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='handler',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handler', to=settings.AUTH_USER_MODEL),
        ),
    ]
