# Generated by Django 3.2 on 2021-06-01 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0015_alter_ordermodel_handler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='handler',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='handler',
            field=models.ManyToManyField(blank=True, null=True, related_name='handler', to=settings.AUTH_USER_MODEL),
        ),
    ]
