# Generated by Django 3.2 on 2021-06-01 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0016_auto_20210601_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='handler',
            field=models.ManyToManyField(blank=True, related_name='handler', to=settings.AUTH_USER_MODEL),
        ),
    ]
