# Generated by Django 3.2 on 2021-06-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_ordermodel_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='license',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
