# Generated by Django 3.2 on 2021-06-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.category'),
            preserve_default=False,
        ),
    ]
