# Generated by Django 3.2 on 2021-06-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_tracker_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.category'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='image',
            field=models.ImageField(upload_to='contract_images/'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
