# Generated by Django 3.2 on 2021-06-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20210604_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='image',
            new_name='contract_image',
        ),
    ]
