# Generated by Django 3.2 on 2021-06-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_tracker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='type',
            field=models.CharField(choices=[('1', '追加'), ('2', '返品')], default='1', max_length=100),
        ),
    ]
