# Generated by Django 3.2 on 2021-06-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_ordermodel_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='location_selecter',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
