# Generated by Django 3.2 on 2021-06-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_ordermodel_location_selecter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
