# Generated by Django 3.2 on 2021-05-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_permission_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='permission',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
