# Generated by Django 3.2 on 2021-05-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_permission_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='comment',
            field=models.CharField(blank=True, default='コメント作成', max_length=100),
        ),
    ]
