# Generated by Django 3.2 on 2021-05-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_permission_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
