# Generated by Django 3.2 on 2021-06-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='first',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='text',
            name='second',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='text',
            name='third',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
