# Generated by Django 3.2 on 2021-06-03 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_alter_permission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='user',
        ),
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
