# Generated by Django 3.2 on 2021-06-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210603_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='image',
        ),
        migrations.AddField(
            model_name='permission',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
