# Generated by Django 3.2 on 2021-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_permission_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contract_images/'),
        ),
    ]
