# Generated by Django 3.2 on 2021-06-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210607_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
