# Generated by Django 3.2 on 2021-06-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210609_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='start_date',
            field=models.DateField(),
        ),
    ]
