# Generated by Django 3.2 on 2021-06-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20210610_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
