# Generated by Django 3.2 on 2021-06-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210610_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
