# Generated by Django 3.2 on 2021-06-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20210610_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='comment',
        ),
    ]
