# Generated by Django 3.2 on 2021-06-14 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_remove_permission_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2048, 10, 29, 14, 32, 34, 347925), null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(1994, 1, 28, 14, 32, 34, 347925), null=True),
        ),
    ]
