# Generated by Django 3.2 on 2021-05-28 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210528_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
