# Generated by Django 3.2 on 2021-05-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='limit',
            field=models.IntegerField(default=100000),
        ),
    ]
