# Generated by Django 3.1.7 on 2021-04-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210429_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.client'),
        ),
    ]
