# Generated by Django 3.2 on 2021-06-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_limit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='license',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='facility',
            field=models.CharField(max_length=100),
        ),
    ]
