# Generated by Django 3.2 on 2021-06-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210603_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='license',
        ),
    ]
