# Generated by Django 3.2 on 2021-06-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_client_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
    ]
