# Generated by Django 3.2 on 2021-04-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210430_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
