# Generated by Django 3.2 on 2021-04-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210430_0803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
