# Generated by Django 3.1.7 on 2021-05-03 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_client_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='is_read',
            new_name='it_read',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='date',
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.threadmodel'),
        ),
    ]
