# Generated by Django 3.1.7 on 2021-05-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210504_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(default='default.jpg', upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('手すり', '手すり'), ('車いす', '車いす'), ('ベッド', 'ベッド')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('新商品', '新商品'), ('人気商品', '人気商品'), ('割引商品', '割引商品')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
