# Generated by Django 3.2 on 2021-05-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_ordermodel_is_paid'),
        ('home', '0026_alter_client_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.ordermodel'),
        ),
    ]
